local_backend: true

backend:
  name: github
  repo: lucascapistrant/mgxcwebsite
  branch: main
  # for deployment:
  base_url: https://mgxc-decap-cms-oauth.vercel.app/
  auth_endpoint: /auth

media_folder: "public/images"
public_folder: "/images"

logo:
  src: /public/mgxc_logo.png
  show_in_header: true

collections:
  - name: "sponsors"
    label: "Sponsors"
    folder: "src/content/sponsors"
    create: true
    fields:
      - { label: "Sponsor Logo", name: "sponsor_logo", widget: "image", required: true }
      - { label: "Sponsor Name", name: "sponsor_name", widget: "string", required: true }
      - { label: "Company Website Link", name: "company_link", widget: "string" }
  - name: "hero-images"
    label: "Front page images"
    folder: "src/content/hero-images"
    create: true
    fields:
      - {label: "Featured Image", name: "hero_image", widget: "image"}
  - name: "posts"
    label: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "MMM, DD, YYYY" }
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Body Text", name: "body", widget: "markdown", required: false }
  - name: "schedule"
    label: "Schedule"
    folder: "src/content/schedule"
    create: true
    fields:
      - { label: "Event Name", name: "event_name", widget: "string" }
      - { label: "Event Date", name: "event_date", widget: "datetime", format: "MMM, DD, YYYY h:mm A" }
      - { label: "Event Location", name: "event_location", widget: "string", required: false }
      - { label: "Event Description", name: "event_description", widget: "markdown", required: false }
  - name: "records"
    label: "Records"
    folder: "src/content/records"
    create: true
    fields:
      - { label: "Record Type", name: "record_type", widget: "select", options: ["5k Race", "2 Mile Race"] }
      - { label: "Athlete Gender", name: "record_gender", widget: "select", options: ["Male", "Female"] }
      - { label: "Athlete Name", name: "athlete_name", widget: "string" }
      - { label: "Race Time Minutes", name: "race_time_minutes", widget: "number", min: 0, max: 59 }
      - { label: "Race Time Seconds", name: "race_time_seconds", widget: "number", min: 0, max: 59 }
      - { label: "Race Time Milliseconds", name: "race_time_milliseconds", widget: "number", min: 0, max: 999, required: false }
  - name: "coaches"
    label: "Coaches"
    folder: "src/content/coaches"
    create: true
    fields:
      - { label: "Coach Type", name: "coach_type", widget: "select", options: ["Head Coach", "Assistant Coach"] }
      - { label: "Coach Name", name: "coach_name", widget: "string" }
      - { label: "Coach Photo", name: "coach_photo", widget: "image" }
      - { label: "Coach Contact Info", name: "coach_contact_info", widget: "string", required: false, hint: "Email or phone number" }
      - { label: "Coach Bio", name: "coach_bio", widget: "markdown", required: false }
  - name: "site-information"
    label: "Site Information"
    files:
      - label: "Site Links"
        name: "site_links"
        file: "src/content/site-links.json"
        fields:
          - { label: "Instagram Link", name: "instagram_link", widget: "string" }
          - { label: "GitHub Link", name: "github_link", widget: "string" }
          - { label: "X Link", name: "x_link", widget: "string" }
          - { label: "SafeTeam Link", name: "safeteam_link", widget: "string" }
          - { label: "Track and Field Link", name: "track_and_field_link", widget: "string" }
          - { label: "Nordic Link", name: "nordic_link", widget: "string" }
      - label: "Summer Practice Info"
        name: "schedule_info"
        file: "src/content/summer-training-info.json"
        fields:
          - { label: "Introduction Image", name: "introduction_image", widget: "image" }
          - { label: "Introduction Header", name: "introduction_header", widget: "string" }
          - { label: "Introduction Paragraph", name: "introduction_paragraph", widget: "markdown" }
          - { label: "Communication Text", name: "communication_text", widget: "markdown" }
          - { label: "What? Text", name: "what_text", widget: "markdown" }
          - { label: "When? Text", name: "when_text", widget: "markdown" }
          - { label: "Where? Text", name: "where_text", widget: "markdown" }
          - { label: "Who? Text", name: "who_text", widget: "markdown" }
      - label: "Handbook"
        name: "handbook"
        file: "src/content/handbook.json"
        fields:
          - label: "Upload PDF"
            name: "handbook_pdf"
            widget: "file"
            required: true
            media_library:
              config:
                allowed_mime_types: ["application/pdf"]